### ISSUE TITLE
build fails for recent linux / glibc

### ISSUE THREAD

**Issue by ploxiln** [tsgates/mbox#3]
On my system (archlinux, linux kernel 3.12, glibc 2.18) mbox fails to build because of multiple definitions of `struct ptrace_peeksiginfo_args` between `kernel/strace.h` and `sys/strace.h`. My quick fix just to get a build I could play with was:

``` diff
diff --git a/src/process.c b/src/process.c
index fa304e5..c249e1e 100644
--- a/src/process.c
+++ b/src/process.c
@@ -60,6 +60,7 @@
 # ifdef HAVE_STRUCT_PT_ALL_USER_REGS
 #  define pt_all_user_regs XXX_pt_all_user_regs
 # endif
+# define ptrace_peeksiginfo_args XXX_ptrace_peeksiginfo_args
 # include <linux/ptrace.h>
 # undef ia64_fpreg
 # undef pt_all_user_regs
```

As far as I can see that should be good for any situation, but I'd imagine you might prefer to have configure checks and macros and such, maybe taking them from the latest strace, etc.

**Comment by tsgates** [comment]
thanks! applied.

**Comment by ploxiln** [comment]
I expected you would have closed this yourself :)
it is indeed fixed
